<#
.SYNOPSIS
    Intune Win32 app - custom DETECTION script (upload in Intune > Detection rules > Use a custom detection script).
    Not packaged into the .intunewin.

.DESCRIPTION
    Detected  = writes output and exits 0.
    Not found = no output, exits 0.
    Update $MinimumVersion each time you package a new version.

    Generated by New-IntuneApp.ps1 from Templates\Detect.ps1.template - re-run New-IntuneApp.ps1 rather than editing by hand.
#>

$DisplayName    = 'PowerShell 7-x64'
$MinimumVersion = '7.6.6.0'

$paths = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
         'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'

$App = Get-ItemProperty -Path $paths -ErrorAction SilentlyContinue |
       Where-Object { $_.DisplayName -like $DisplayName } |
       Select-Object -First 1

function ConvertTo-Version([string]$Text) {
    if ($Text -match '(\d+(\.\d+){1,3})') {
        $parts = [System.Collections.Generic.List[string]]$Matches[1].Split('.')
        while ($parts.Count -lt 4) { $parts.Add('0') }
        return [version]($parts -join '.')
    }
    return $null
}

$Installed = if ($App) { ConvertTo-Version $App.DisplayVersion }
if ($Installed -and $Installed -ge (ConvertTo-Version $MinimumVersion)) {
    Write-Output "Detected: $($App.DisplayName) $($App.DisplayVersion)"
}
exit 0
