<#
.SYNOPSIS
    Intune Win32 app - UNINSTALL script.

.DESCRIPTION
    Finds the app in Add/Remove Programs and removes it silently.
    Handles both EXE uninstallers (Inno Setup, NSIS, etc.) and MSI products.
    Waits until the uninstall entry is gone before reporting success.
    Log: C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\<AppName>-Uninstall.log

.NOTES
    Intune uninstall command:
        powershell.exe -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -File .\Uninstall-Obsidian.ps1
    Exit codes: 0 = success/not installed, 3010 = success/reboot required, 1618 = retry, 1 = failure

    Generated by New-IntuneApp.ps1 from Templates\Uninstall.ps1.template - re-run New-IntuneApp.ps1 rather than editing by hand.
#>

#region ---------------- App configuration (edit per app) ----------------
$AppName          = 'Obsidian'
$DisplayName      = '*Obsidian*'     # DisplayName in Add/Remove Programs (-like pattern)
$UninstallArgs    = '/S'  # Args for EXE uninstallers (ignored for MSI)
$ProductCode      = ''  # MSI ProductCode - looked up first if set (blank for EXE apps)
$ProcessesToClose = @()
$TimeoutSeconds   = 300                                # Max wait for the uninstall entry to disappear
#endregion ------------------------------------------------------------------

if ($env:PROCESSOR_ARCHITEW6432 -eq 'AMD64' -and -not [Environment]::Is64BitProcess) {
    & "$env:WINDIR\SysNative\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -NoProfile -File $PSCommandPath
    exit $LASTEXITCODE
}

#region ---------------- Helpers ----------------
$LogDir = "$env:ProgramData\Microsoft\IntuneManagementExtension\Logs"
if (-not (Test-Path $LogDir)) { New-Item -Path $LogDir -ItemType Directory -Force | Out-Null }
$LogFile  = Join-Path $LogDir "$AppName-Uninstall.log"
$SetupLog = Join-Path $LogDir "$AppName-Uninstall-Setup.log"

function Write-Log {
    param([string]$Message, [ValidateSet('INFO','WARN','ERROR')][string]$Level = 'INFO')
    $line = '{0} [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -Path $LogFile -Value $line
    Write-Host $line
}

function Get-InstalledApp {
    $roots = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall',
             'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall'
    if ($ProductCode) {
        $byCode = $roots | ForEach-Object { Get-ItemProperty -LiteralPath (Join-Path $_ $ProductCode) -ErrorAction SilentlyContinue } |
                  Select-Object -First 1
        if ($byCode) { return $byCode }
    }
    Get-ItemProperty -Path ($roots | ForEach-Object { "$_\*" }) -ErrorAction SilentlyContinue |
        Where-Object { $_.DisplayName -like $DisplayName } |
        Select-Object -First 1
}

function Stop-AppProcess {
    foreach ($name in $ProcessesToClose) {
        Get-Process -Name $name -ErrorAction SilentlyContinue | ForEach-Object {
            Write-Log "Closing $($_.ProcessName) (PID $($_.Id))"
            $_ | Stop-Process -Force -ErrorAction SilentlyContinue
        }
    }
}
#endregion -------------------------------------------

try {
    Write-Log "===== $AppName uninstall started ====="

    $App = Get-InstalledApp
    if (-not $App) {
        Write-Log "'$DisplayName' is not installed - nothing to do."
        exit 0
    }
    Write-Log "Found: $($App.DisplayName) $($App.DisplayVersion)"
    Write-Log "UninstallString: $($App.UninstallString)"

    Stop-AppProcess

    $UninstallString = $App.UninstallString

    # MSI product? (registry key name is the ProductCode, or the UninstallString calls msiexec)
    $MsiCode = $null
    if ($App.WindowsInstaller -eq 1 -and $App.PSChildName -match '^\{[0-9A-Fa-f\-]{36}\}$') { $MsiCode = $App.PSChildName }
    elseif ($UninstallString -match 'msiexec' -and $UninstallString -match '(\{[0-9A-Fa-f\-]{36}\})') { $MsiCode = $Matches[1] }

    if ($MsiCode) {
        $FilePath  = "$env:WINDIR\System32\msiexec.exe"
        $Arguments = "/x $MsiCode /qn /norestart /l*v `"$SetupLog`""
    }
    elseif (-not $UninstallString) {
        throw 'No UninstallString found in the registry.'
    }
    elseif ($UninstallString -match '^\s*"?(.+?\.exe)"?') {
        # EXE uninstaller (quoted or unquoted path)
        $FilePath  = $Matches[1]
        $Arguments = $UninstallArgs
    }
    else {
        throw "Could not parse UninstallString: $UninstallString"
    }

    if (-not (Test-Path $FilePath)) { throw "Uninstaller not found: $FilePath" }
    Write-Log "Running: `"$FilePath`" $Arguments"

    $Process  = Start-Process -FilePath $FilePath -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
    $ExitCode = $Process.ExitCode
    Write-Log "Uninstaller exit code: $ExitCode"
    if ($ExitCode -eq 1618) { Write-Log 'Another installation is in progress (1618) - Intune will retry.' 'WARN'; exit 1618 }
    if ($ExitCode -notin 0, 1605, 1641, 3010) { throw "Uninstaller failed with exit code $ExitCode" }

    # Some uninstallers (e.g. Inno Setup) hand off to a temp copy and return early - wait for the entry to go away
    $Elapsed = 0
    while ((Get-InstalledApp) -and $Elapsed -lt $TimeoutSeconds) {
        Start-Sleep -Seconds 5
        $Elapsed += 5
    }
    if (Get-InstalledApp) { throw "'$DisplayName' is still registered after $TimeoutSeconds seconds." }
    Write-Log "Verified '$DisplayName' is removed."

    if ($ExitCode -in 1641, 3010) { Write-Log 'Reboot required.'; exit 3010 }
    Write-Log "===== $AppName uninstall completed successfully ====="
    exit 0
}
catch {
    Write-Log $_.Exception.Message 'ERROR'
    Write-Log "===== $AppName uninstall FAILED =====" 'ERROR'
    exit 1
}
